discourse/discourse-oauth2-basic

- plugin.rb
Improvement of 2b9869e (FEATURE: If the email is verified, we can use that to find accounts): Downcasing the email which has been got from the OAuth provider, as the email entity is not case-sensitive in Discourse. I've provided more information in the https://meta.discourse.org/t/oauth2-basic-support/33879/31
Thanks!
> Improvement: downcase the email when searching for an account by email

- plugin.rb
- spec/plugin_spec.rb
See: https://meta.discourse.org/t/custom-oauth2-fails-for-newly-created-accounts-related-to-user-emails/69406
This should also be backwards compatible with users on Discourse branch not using `user_emails`, as `User.find_by_email` existed before the migration.
> FIX: make work with user_emails migration

- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
this would give the oauth2-basic plugin an option to use full screen login when combined with this PR https://github.com/discourse/discourse/pull/6180
> Add site setting to allow full screen login

- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
- spec/plugin_spec.rb
This allows a provider to set a user's email verification state by identifying the relevant email verification property in the user object. An example of such is: https://developers.digitalocean.com/documentation/v2/#get-user-information "email_verified"
> Allow provider to set email verification state

- config/locales/server.en.yml
- config/settings.yml
- lib/validators/oauth2_basic/oauth2_fetch_user_details_validator.rb
- plugin.rb
- spec/plugin_spec.rb
A number of OAuth2 implementations include details about the user in the response to an access token request. Here are some examples:
- [DigitalOcean](https://developers.digitalocean.com/documentation/oauth/#request-access-token): name, email and user id
- [Instagram](https://www.instagram.com/developer/authentication/): user id, username, name and profile picture (avatar)
- [FitBit](https://dev.fitbit.com/build/reference/web-api/oauth2/#access-token-request): user id
- [Asana](https://asana.com/developers/documentation/getting-started/auth#token-exchange): user id, name, email
In some cases (somewhat surprisingly) this includes information about the user that is not available in a user endpoint request, for example the DigitalOcean API provides a user's name in the access token response, …
> Use token callback user details

- config/locales/server.en.yml
- plugin.rb
- spec/plugin_spec.rb
There are a few different instances in which an authorization request can succeed and the subsequent user request can fail. For example:
- The user resource may be handled by a different server which has a different status. 
- The user's account state with the provider may permit authorization, but not permit retrieval of user details from the user endpoint, (e.g. it is "Deactivated", or "Disabled").
- Authorization may be persisted on the provider or OmniAuth prior to an account state change which prevents the user endpoint from working.
This PR makes two improvements
1. Currently, two different libraries are used to perform the http request in get_user_details. This reduces this to one (Excon), slightly simplifying the request logic, and also allowing standardised handling of the …
> Handle fetch user details failure

- config/locales/server.en.yml
- config/settings.yml
- db/migrate/20190724055909_move_to_managed_authenticator.rb
- plugin.rb
- spec/plugin_spec.rb
This PR follows up on the [discussion here](https://meta.discourse.org/t/oauth2-basic-support/33879/187?u=angus). It does two things:
1. Turns the ``OAuth2BasicAuthenticator`` class into an extension of ``Auth::ManagedAuthenticator`` instead of ``Auth::OAuth2Authenticator``. Mostly this involves moving the after_authenticate result and user handling to the standardised ``Auth::ManagedAuthenticator`` after_authenticate method.
2. Migrates the existing storage of associated user details from ``PluginStore`` to ``UserAssoicatedAccount``.
The existing tests are all passing and existing implementations should not be affected.
> Move to ManagedAuthenticator

- plugin.rb
- spec/plugin_spec.rb
Hi!
The way the old json walk worked prevented us from pulling the email address out of the json response our oauth provider sent back. The format looked something like 
```
{ "emails" : 
[ { "value" : "theemail@adress.com"} ]
}
```
The old way would return { "value" : "theemail@address.com"}, where of course we only wanted the value of "value".
It is changed so now you can write your path like
`emails[index].value`
to get it, or if you do `emails.value` it will still default to an index of 0 so as not to break old paths.
> allow the json path walk method to parse array indexes

- plugin.rb
- spec/plugin_spec.rb
This is achieved by surrounding a key with double quotes, or by escaping
the dot character with a backslash.
For example, given the JSON
```
{ "www.example.com/uid": "myuid" }
```
Previously, there was no way to access this value. The dots would make
the parser try to access `json["www"]["example"]["com/uid"]`.
Now, this value can be accessed by using a `oauth2_json_user_id_path` like:
```
www\.example\.com/uid
```
or alternatively:
```
"www.example.com/uid"
```
> FEATURE: Allow JSON paths with literal dots in the keys

- plugin.rb
- Remove Faraday version check - all versions of Discourse now have Faraday 1.0
- Remove custom button CSS. Core now takes care of styling login buttons
- Remove deprecated `message` parameter from auth_provider registration
> DEV: Clean up plugin.rb

- plugin.rb
- spec/plugin_spec.rb
Some identity providers send email_verfied as a 'true'/'false' string, not a boolean. (e.g. this bug in Auth0: https://community.auth0.com/t/27553)
This commit adds automatic handling for this case, so that the string is automatically converted into a real boolean.
> FEATURE: Handle invalid email_verified data from identity provider

- config/settings.yml
It can be useful for homegrown CSRF setups or while debugging but it is
not secure and should only be used if you really know what you're doing.
> Hide the `oauth2_disable_csrf` setting

- spec/plugin_spec.rb
``after_create_account`` expects an instance of ``Auth::Result`` as the second arg. Passing the session data hash instead was previously fine as no logic in ``after_create_account`` used instance methods. See further: https://github.com/discourse/discourse/pull/14835#discussion_r755135921
> Update spec to be compliant with ``after_create_account`` expectations

- spec/integration/overrides_email_spec.rb
- spec/plugin_spec.rb
We're moving the location of the email-overriding logic in https://github.com/discourse/discourse/pull/15378, which makes the old unit test in this plugin fail. This commit makes it an integration test, so that it's more robust against core changes, and will continue to pass before and after the core changes.
> DEV: Make overrides_email an integration spec

- plugin.rb
As we’re upgrading Discourse to Rails 7+, we’re also renaming and moving some files to better follow Rails conventions on that matter.
The current `require_dependency` call prevents us to do that and is not necessary as the file referenced here is part of the autoload path.
---
For reference: https://github.com/discourse/discourse/pull/15649
> DEV: Remove unnecessary require

- spec/plugin_spec.rb
The `#queue_jobs=` method on site settings has been [deprecated](https://github.com/discourse/discourse/commit/1b65469b64e9e569fed67ae11f1dd9ee37702f5c) and replaced by `Jobs.run_later!` and `Jobs.run_immediately!`. This PR replaces usages in this plugin so we can remove the fallback in core.
The fallback used in core for reference:
https://github.com/discourse/discourse/blob/main/app/models/site_setting.rb#L109-L115
> DEV: Replace deprecated queue_jobs site setting in tests

- plugin.rb
WIP - needs testing and possible finessing
For verbose logging, use `to_yaml` to format objects in a more readable way
> Better verbose logging

- config/settings.yml
Some APIs require PUT for this call instead of the existing GET or POST options.
> Add support for PUT verb for auth token URL

- plugin.rb
- spec/plugin_spec.rb
It is a configuration error to set `oauth2_fetch_user_details` to true but leave `oauth2_user_json_url` empty.
Before, this resulted in an unhandled exception in core. Now it is checked for here.
> FIX: do not attempt to fetch user JSON if URL is not set

- plugin.rb
- spec/plugin_spec.rb
When retrieving `userinfo` with `oauth2_fetch_user_details=true`, we sometimes want to disallow account creation if an attribute is not fulfilled.
This PR adds a new register `oauth2_basic_required_json_path` which will kick in when retrieving `userinfo`. It can be used this way:
```
DiscoursePluginRegistry.register_oauth2_basic_required_json_path({
path: "extra:account.is_allowed_member",
required_value: true,
error_message: I18n.t("login.unfulfilled_requirement"),
}, self)
```
If the attribute does not satisfy the required value, we will see the specified error message when returning to the forum. The account is not created.
The alternatives I can think of is
1. monkey patching 
2. creating a new authenticator 
(1) is definitely brittle, and (2) does feel like there will be a lot of …
> FEATURE: Allow specifiying required paths when retrieving userinfo

- lib/oauth2_basic_authenticator.rb
- spec/plugin_spec.rb
Currently, in a user json with `false` values, due to a `||` operator, the value incorrectly evaluates to the right hand side. This was causing an issue.
e.g.
```
deref = fragment[first_seg] || fragment[first_seg.to_sym]
```
This PR fixes that and appropriately assigns `false` to the specified path for user details.
> FIX: Appropriately assign  values when fetching user details

- db/migrate/20190724055909_move_to_managed_authenticator.rb
We are adding the Rails/ReversibleMigrationMethodDefinition cop to rubocop-discourse, this change resolves existing errors under this rule.
> DEV: resolve Rails/ReversibleMigrationMethodDefinition errors

- README.md
- config/locales/client.en.yml
From "Login" to "OAuth2 Login" so that it is easier to distinguish from the other login methods.
> UX: Update name in admin plugins page
